version: '3'

services:
  minioserver:
    container_name: minio-demo
    image: minio/minio
    restart: always
    volumes:
      - ~/data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio.user
      MINIO_ROOT_PASSWORD: minio.pass
    command: server /data --console-address ":9001"
